### ISSUE TITLE
Action not found

### ISSUE THREAD

**Issue by kakadiadarpan** [blombard/review-reminder#12]
Hey @blombard! Thanks for making this action, I tried using it but got the below error 😓 

![Screenshot 2021-08-13 at 10 40 34](https://user-images.githubusercontent.com/10805593/129329910-590d306a-4d9c-4741-93d9-e5b63c7670f7.png)

Configuration:
```yml
on:
    schedule:
        - cron: '*/30 * * * 1-5'
        # At every 30th minute on every day-of-week from Monday through Friday.

jobs:
    deploy:
        name: Review reminders
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: blombard/review-reminder@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  reminder-comment: '🏓 please review this PR.'
                  days-before-reminder: '1'

```

Am I doing something wrong here? 🤔

**Comment by blombard** [comment]
Hey, @kakadiadarpan Thank you for pointing me this bug. 
It was a small typo. It should be fixed now in v0.2.

**Comment by kieranklaassen** [comment]
Still have this issue:

![Update and rename main yml to review_reminder yml · Vinebasevinebase@d17783c- Google Chrome](https://user-images.githubusercontent.com/209089/132870908-a2d1969e-eb15-47f7-94a5-0e112e8ad5ff.jpg)

**Comment by fpringle** [comment]
@kieranklaassen did you ever work out a fix for this issue?

**Comment by yu-iskw** [comment]
@blombard I still have the issue. My implementation using the action is the same as that in `README.md`.

**Comment by blombard** [comment]
Hello @fpringle @yu-iskw I think I fixed the issue in the [v0.3 release](https://github.com/blombard/review-reminder/releases/tag/v0.3).

Could you kindly test if it works on your side?

**Comment by yu-iskw** [comment]
@blombard Thank you for the quick fixing! I will give it a try on my repository.

**Comment by fpringle** [comment]
@blombard still not working :( this is the error I got:

```Run blombard/review-reminder@master
(node:1637) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/blombard/review-reminder/master/dist/index.js:3482:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1637) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

(node:1637) UnhandledPromiseRejectionWarning: HttpError: Not Found
    at /home/runner/work/_actions/blombard/review-reminder/master/dist/index.js:3482:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1637) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by blombard** [comment]
@fpringle Sorry for this, I deployed a new fix for your issue. (I'm paying the lack of testing...)

**Comment by fpringle** [comment]
@blombard looks good, no more errors :)
